name: Auto approve

on:
  pull_request:
    types:
      - labeled

jobs:
  autoapprove:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      if: github.actor == 'pull[bot]'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
